# Generated by Django 6.0.4 on 2026-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
